@echo off
chcp 65001 >nul
set PYTHONIOENCODING=utf-8

echo === Building ESP-NOW Audio Source ===
cd /d "D:\ESP32-Code\esp-now-audio-source"
call "D:\Bluetooth Project - Copy\esp-idf\export.bat"

idf.py build
if %ERRORLEVEL% NEQ 0 (
    echo === BUILD FAILED ===
    exit /b 1
)
echo === BUILD SUCCESSFUL ===

echo.
echo === Flashing firmware + SPIFFS music partition ===
echo (connect the source ESP32 and update the COM port below if needed)
echo.

REM Flash firmware, partitions, bootloader, AND the SPIFFS music image in one go.
REM idf.py flash handles all partitions including the spiffs image generated by
REM spiffs_create_partition_image(music ../data FLASH_IN_PROJECT).
idf.py -p COM4 flash

if %ERRORLEVEL% NEQ 0 (
    echo === FLASH FAILED (check COM port) ===
    exit /b 1
)

echo.
echo === Flash complete – starting monitor (Ctrl+] to exit) ===
idf.py -p COM4 monitor
